### ISSUE TITLE
Ensure every method handles errors gracefully.

### ISSUE THREAD

**Issue by ice-breaker-tg** [web3-storage/w3up-client#40]
example in #34 not explaining that account not setup/etc.

**Comment by alanshaw** [comment]
This issue is too open ended. Ucanto is generally very good at responding with good messages for UCAN calidation/verification issues. In #34 it looks like the actual handler is throwing - and it should instead be verifying that a user has access to uplaod to a space. We have a re-written and tested backend now so this is unlikely to occur again without a better message.

The specific problem with no space in #34 is handled already so I'm going to close this and we'll re-open if badly handled errors are experienced.
